services:
  jenkins:
    image: jenkins/jenkins # Use the recommended LTS image
    user: "0"
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080" # Web UI port
      - "50000:50000" # Agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home # Mount a volume for data persistence
      - ./laravel-project:/var/jenkins_home/workspace/laravel-src
      - /var/run/docker.sock:/var/run/docker.sock # Allows Jenkins to interact with the host's Docker daemon (optional, for "Docker-in-Docker" scenarios)
      - /usr/bin/docker:/usr/bin/docker

networks:
  jenkins_network:
    driver: bridge
volumes:
  jenkins_home:
    driver: local
