services:
  laravel-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel-dev
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www